#! /bin/sh

set -e -x

mkdir -p $SNAP_DATA/var/spool/tmp
mkdir -p $SNAP_DATA/var/run/certs
mkdir -p $SNAP_DATA/var/log
mkdir -p $SNAP_DATA/var/cache/fontconfig
mkdir -p $SNAP_COMMON/etc/ppd
mkdir -p $SNAP_COMMON/etc/fonts

CUPSFILESCONF=$SNAP/etc/cups/cups-files.conf
CUPSDCONF=$SNAP/etc/cups/cupsd.conf
SCHEDULER=cupsd
FONTSCONF=$SNAP/etc/fonts/fonts.conf
PORT=631
DOMAINSOCKET=$SNAP_DATA/var/run/cups.sock

# Set UTF-8
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# Set a general TMPDIR
export TMPDIR=$SNAP_DATA/tmp
mkdir -p $TMPDIR

# Activate full debug logging of cupsd and libcups
# Activate debug logging of the libcups used by cups-browsed
# (Needs "- --enable-debug-printfs" be uncommented in CUPS' configflags
#export CUPS_DEBUG_LOG=$SNAP_DATA/var/log/debug_log
#export CUPS_DEBUG_LEVEL=99

cp $SNAP/etc/cups/snmp.conf $SNAP_COMMON/etc/
cp -r $SNAP/etc/cups/ppd $SNAP_COMMON/etc/
cp -r $SNAP/etc/cups/ssl $SNAP_COMMON/etc/
cat $CUPSFILESCONF | perl -p -e 's:^(\s*)\#?(\s*\S+\s+)/:\1\2'"$SNAP"'/:g' | perl -p -e 's:^(\s*)\#?(\s*\S+\s+)\S*/var/(\S*?)/cups(.*)$:\1\2'"$SNAP_DATA"'/var/\3\4:g' | perl -p -e 's:^(\s*)\#?(\s*\S+\s+)\S*/etc:\1\2'"$SNAP_COMMON"'/etc\3\5:g' | perl -p -e 's:/etc/cups:/etc:g' | perl -p -e 's:^(\s*)\#?(User|Group)(\s+)\S+:\1\2\3root:g' | perl -p -e 's:^(\s*)\#?(SystemGroup\s+)\S+:\1\2\3root adm:g' > $SNAP_COMMON/etc/cups-files.conf
cat $CUPSDCONF | grep -v 'Listen' | perl -p -e 's:^(\s*<Location\s*/>\s*)$:$1  Allow \@LOCAL\n:' > $SNAP_COMMON/etc/cupsd.conf

if $SNAP/port-occupied $PORT; then
    # CUPS already running (Debian packages), try alternative port
    if [ -e $SNAP/default.yaml ]; then
	PORT=$(grep -A1 cups $SNAP/default.yaml|\
		   grep altport:|sed "s:.*altport\: ::")
    fi
fi

cat $SNAP_COMMON/etc/cupsd.conf | grep -v Listen | grep -v Port > $SNAP_COMMON/etc/cupsd.conf.new && \
    echo Port $PORT > $SNAP_COMMON/etc/cupsd.conf && \
    cat $SNAP_COMMON/etc/cupsd.conf.new >> $SNAP_COMMON/etc/cupsd.conf && \
    rm $SNAP_COMMON/etc/cupsd.conf.new

cat $SNAP_COMMON/etc/cupsd.conf | grep -v Listen > $SNAP_COMMON/etc/cupsd.conf.new && \
    echo Listen $DOMAINSOCKET > $SNAP_COMMON/etc/cupsd.conf && \
    cat $SNAP_COMMON/etc/cupsd.conf.new >> $SNAP_COMMON/etc/cupsd.conf && \
    rm $SNAP_COMMON/etc/cupsd.conf.new

cat $FONTSCONF | perl -p -e 's:(<dir>)(/):$1'"$SNAP"'$2:' | perl -p -e 's:(<cachedir>)(/):$1'"$SNAP_DATA"'$2:' > $SNAP_COMMON/etc/fonts/fonts.conf

export FONTCONFIG_FILE=$SNAP_COMMON/etc/fonts/fonts.conf

echo PassEnv FONTCONFIG_FILE >> $SNAP_COMMON/etc/cups-files.conf

echo MaxLogSize 9999999 >> $SNAP_COMMON/etc/cupsd.conf

perl -p -i -e 's:^(\s*)\#?(\s*LogLevel\s+)\S+:\1\2debug:g' $SNAP_COMMON/etc/cupsd.conf

# chmod 0640 $SNAP_COMMON/etc/cups-files.conf $SNAP_COMMON/etc/cupsd.conf

#chmod 711 $SNAP_DATA/var/run/certs/
#chown root.root $SNAP_DATA/var/run/certs/

# Spawn cupsd in a way that we can grab its PID
exec $SCHEDULER -f -s $SNAP_COMMON/etc/cups-files.conf -c $SNAP_COMMON/etc/cupsd.conf &
PID=$!
echo $PID > $SNAP_DATA/var/run/cupsd.pid

# Keep this script running until cupsd terminates
wait $PID
