name: printing-stack-snap
version: 0.1.0
summary: CUPS-based printing stack snap
description: Complete printing environment in a snap
grade: devel
confinement: strict

environment:
  CUPS_SERVER: $SNAP_DATA/var/run/cups.sock

apps:
  cupsd:
    command: run-cupsd
    daemon: simple
    plugs: [network, network-bind, avahi-control, raw-usb]
  cups-browsed:
    command: run-cups-browsed
    daemon: simple
    plugs: [network, network-bind, avahi-control]
  lpinfo:
    command: lpinfo
    plugs: [network, avahi-control, raw-usb]
  lpadmin:
    command: lpadmin
    plugs: [network, avahi-control, home]
  lpstat:
    command: lpstat
    plugs: [network, avahi-control]
  lpoptions:
    command: lpoptions
    plugs: [network, avahi-control, home]
  lp:
    command: lp
    plugs: [network, avahi-control, home]
  cancel:
    command: cancel
    plugs: [network, avahi-control]
  cupsenable:
    command: cupsenable
    plugs: [network, avahi-control]
  cupsdisable:
    command: cupsdisable
    plugs: [network, avahi-control]
  cupsaccept:
    command: cupsaccept
    plugs: [network, avahi-control]
  cupsreject:
    command: cupsreject
    plugs: [network, avahi-control]
  accept:
    command: accept
    plugs: [network, avahi-control]
  reject:
    command: reject
    plugs: [network, avahi-control]
  cupsctl:
    command: cupsctl
    plugs: [network, avahi-control]
  cupsfilter:
    command: cupsfilter
    plugs: [network, avahi-control, home]
  cupstestppd:
    command: cupstestppd
    plugs: [network, avahi-control, home]
  cupstestdsc:
    command: cupstestdsc
    plugs: [network, avahi-control, home]
  ipptool:
    command: ipptool
    plugs: [network, avahi-control, home]
  ippfind:
    command: ippfind
    plugs: [network, avahi-control]

parts:
  cups:
    source: https://github.com/apple/cups/releases/download/v2.2.6/cups-2.2.6-source.tar.gz
    plugin: autotools
    prepare: |
        patch -p0 < ../../../cupsd-pass-on-ld-library-path.patch
        patch -p0 < ../../../cupsd-pass-on-path.patch
        patch -p0 < ../../../cupsd-allow-root-as-cups-user.patch
        patch -p0 < ../../../cupsd-allow-group-and-systemgroup-be-the-same.patch
        patch -p0 < ../../../libcups-do-not-read-cupsd-conf-from-local-file.patch
        patch -p0 < ../../../cups-deviced-allow-run-by-root.patch
        sed -i 's|$(DSTROOT)|'"${SNAPCRAFT_PART_INSTALL}"'|g' Make*
        sed -i 's|fchown(cupsFileNumber(fp), getuid(), Group)|0|g' scheduler/file.c
        sed -i 's|(fchmod(cupsFileNumber(fp), mode))|(0)|g' scheduler/file.c
        sed -i 's|chown(filename, user, group)|0|g' scheduler/conf.c
        sed -i 's|setgroups(1, &Group)|0|g' scheduler/process.c
        sed -i 's|setgroups(1, &gid)|0|g' scheduler/cups-exec.c
        sed -i 's|fchown(|// fchown(|g' cups/*.c
        sed -i 's|chown(|// chown(|g' cups/*.c
        sed -i 's|fchmod(|// fchmod(|g' cups/*.c
        sed -i 's|chmod(|// chmod(|g' cups/*.c
        sed -i 's|fchown(|// fchown(|g' scheduler/*.c
        sed -i 's|fchmod(|// fchmod(|g' scheduler/*.c
    configflags:
        - --with-system-groups=root
        - --disable-pam
    build-packages:
        - patch
        - autoconf
        - automake
        - libtool
        - autotools-dev
        - pkg-config
        - ghostscript
        - libavahi-client-dev
        - libavahi-common-dev
        - libavahi-compat-libdnssd-dev
        - libdbus-1-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgnutls28-dev
        - libijs-dev
        - libjpeg-dev
        - libldap2-dev
        - libkrb5-dev
        - libpam0g-dev
        - libpaper-dev
        - libpng-dev
        - libsystemd-dev
        - libtiff5-dev
        - libusb-1.0-0-dev
        - po4a
        - po-debconf
        - poppler-utils
        - sharutils
        - zlib1g-dev
        - wget
  cups-filters:
    source: http://www.openprinting.org/download/cups-filters/cups-filters-1.17.9.tar.xz
    plugin: autotools
    configflags:
        - --with-pdftops=pdftops
        - --disable-ghostscript
        - --disable-mutool
    build-packages:
        - autoconf
        - autotools-dev
        - pkg-config
        - sharutils
        - poppler-utils
        - libglib2.0-dev
        - liblcms2-dev
        - libldap2-dev
        - libpoppler-private-dev
        - libpoppler-cpp-dev
        - libqpdf-dev
        - libjpeg-dev
        - libpng-dev
        - libtiff5-dev
        - libijs-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libdbus-1-dev
        - libavahi-common-dev
        - libavahi-client-dev
        - libavahi-glib-dev
        - librsvg2-bin
        - liblouis-dev
        - fonts-dejavu-core
    stage-packages:
        - poppler-utils
    after: [cups]
  selected-fonts: # Temporary, fonts shpuld come from the system
    plugin: dump
    #source: /usr/share/fonts
    stage-packages:
        - fonts-freefont-ttf
        - fontconfig-config
    prime:
        - usr/share/fonts/*
        - etc/fonts/fonts.conf
    organize: # see lp#1588283
     /usr/share/fonts/truetype/freefont/*.ttf: usr/share/cups/fonts/
     #/etc/fonts/fonts.conf: etc/fonts/fonts.conf
  copy:
    plugin: dump
    #organize:
      #run-cupsd: run-cupsd
      #run-cups-browsed: run-cups-browsed
      #default.yaml: default.yaml
    stage-packages:
        - perl-base
        - sed
        - grep
    after: [cups, cups-filters, selected-fonts]
