name: printing-stack-snap
version: 0.1.0
summary: CUPS-based printing stack snap
description: Complete printing environment in a snap
grade: devel
confinement: strict

environment:
  CUPS_SERVER: $SNAP_DATA/var/run/cups.sock

apps:
  cupsd:
    command: run-cupsd
    daemon: simple
    plugs: [network, network-bind, avahi-control, raw-usb]
  cups-browsed:
    command: run-cups-browsed
    daemon: simple
    plugs: [network, network-bind, avahi-control]
  lpinfo:
    command: lpinfo
    plugs: [network, avahi-control, raw-usb]
  lpadmin:
    command: lpadmin
    plugs: [network, avahi-control, home]
  lpstat:
    command: lpstat
    plugs: [network, avahi-control]
  lpoptions:
    command: lpoptions
    plugs: [network, avahi-control, home]
  lp:
    command: lp
    plugs: [network, avahi-control, home]
  cancel:
    command: cancel
    plugs: [network, avahi-control]
  cupsenable:
    command: cupsenable
    plugs: [network, avahi-control]
  cupsdisable:
    command: cupsdisable
    plugs: [network, avahi-control]
  cupsaccept:
    command: cupsaccept
    plugs: [network, avahi-control]
  cupsreject:
    command: cupsreject
    plugs: [network, avahi-control]
  accept:
    command: accept
    plugs: [network, avahi-control]
  reject:
    command: reject
    plugs: [network, avahi-control]
  cupsctl:
    command: cupsctl
    plugs: [network, avahi-control]
  cupsfilter:
    command: cupsfilter
    plugs: [network, avahi-control, home]
  cupstestppd:
    command: cupstestppd
    plugs: [network, avahi-control, home]
  cupstestdsc:
    command: cupstestdsc
    plugs: [network, avahi-control, home]
  ipptool:
    command: ipptool
    plugs: [network, avahi-control, home]
  ippfind:
    command: ippfind
    plugs: [network, avahi-control]

parts:
  cups:
    source: https://github.com/apple/cups/releases/download/v2.3.1/cups-2.3.1-source.tar.gz
    plugin: autotools
    override-build: |
        patch -p0 < ../../../cupsd-pass-on-ld-library-path.patch
        patch -p0 < ../../../cupsd-pass-on-path.patch
        patch -p0 < ../../../cupsd-allow-root-as-cups-user.patch
        patch -p0 < ../../../cupsd-allow-group-and-systemgroup-be-the-same.patch
        patch -p0 < ../../../libcups-do-not-read-cupsd-conf-from-local-file.patch
        patch -p0 < ../../../cups-deviced-allow-run-by-root.patch
        sed -i 's|$(DSTROOT)|'"${SNAPCRAFT_PART_INSTALL}"'|g' Make*
        sed -i 's|fchown(cupsFileNumber(fp), getuid(), Group)|0|g' scheduler/file.c
        sed -i 's|(fchmod(cupsFileNumber(fp), mode))|(0)|g' scheduler/file.c
        sed -i 's|chown(filename, user, group)|0|g' scheduler/conf.c
        sed -i 's|setgroups(1, &Group)|0|g' scheduler/process.c
        sed -i 's|setgroups(1, &gid)|0|g' scheduler/cups-exec.c
        sed -i 's|fchown(|// fchown(|g' cups/*.c
        sed -i 's|chown(|// chown(|g' cups/*.c
        sed -i 's|fchmod(|// fchmod(|g' cups/*.c
        sed -i 's|chmod(|// chmod(|g' cups/*.c
        sed -i 's|fchown(|// fchown(|g' scheduler/*.c
        sed -i 's|fchmod(|// fchmod(|g' scheduler/*.c
        snapcraftctl build
    stage:
        - -var/spool/cups/tmp
    configflags:
        - --with-system-groups=root
        - --disable-pam
    build-packages:
        - patch
        - autoconf
        - automake
        - libtool
        - autotools-dev
        - pkg-config
        - ghostscript
        - libavahi-client-dev
        - libavahi-common-dev
        - libavahi-compat-libdnssd-dev
        - libdbus-1-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgnutls28-dev
        - libijs-dev
        - libjpeg-dev
        - libldap2-dev
        - libkrb5-dev
        - libpam0g-dev
        - libpaper-dev
        - libpng-dev
        - libsystemd-dev
        - libtiff5-dev
        - libusb-1.0-0-dev
        - po4a
        - po-debconf
        - poppler-utils
        - sharutils
        - zlib1g-dev
        - wget
    stage-packages:
        - libusb-1.0-0
        - libavahi-common3
        - libavahi-client3
  qpdf:
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-9.1.0/qpdf-9.1.0.tar.gz
    plugin: autotools
    build-packages:
        - libjpeg-dev
        - zlib1g-dev
  cups-filters:
    source: http://www.openprinting.org/download/cups-filters/cups-filters-1.26.0.tar.xz
    plugin: autotools
    configflags:
        - --with-pdftops=pdftops
        - --disable-ghostscript
        - --disable-mutool
    build-packages:
        - autoconf
        - autotools-dev
        - pkg-config
        - sharutils
        - poppler-utils
        - libglib2.0-dev
        - liblcms2-dev
        - libldap2-dev
        - libpoppler-private-dev
        - libpoppler-cpp-dev
        - libjpeg-dev
        - libpng-dev
        - libtiff5-dev
        - libijs-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libdbus-1-dev
        - libavahi-common-dev
        - libavahi-client-dev
        - libavahi-glib-dev
        - librsvg2-bin
        - liblouis-dev
        - fonts-dejavu-core
    stage-packages:
        - poppler-utils
        - libasn1-8-heimdal
        - libavahi-glib1
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libkrb5-26-heimdal
        - libldap-2.4-2
        - libroken18-heimdal
        - libsasl2-2
        - libwind0-heimdal
        - libdb5.3
    after: [cups, qpdf]
  selected-fonts: # Temporary, fonts shpuld come from the system
    plugin: nil
    source: .
    stage-packages:
        - fonts-freefont-ttf
    prime:
        - usr/share/fonts/*
    override-stage: |
        mkdir -p $SNAPCRAFT_STAGE/usr/share/cups/fonts/
        cp /usr/share/fonts/truetype/freefont/*.ttf $SNAPCRAFT_STAGE/usr/share/cups/fonts/
        snapcraftctl stage
  copy:
    plugin: nil
    stage-packages:
        - perl-base
        - sed
        - grep
    after: [cups, cups-filters, selected-fonts]
