name: printing-stack-snap
base: core18 # The base snap is the execution environment for this snap
version: 0.1.0
summary: CUPS-based printing stack snap
description: Complete printing environment in a snap
grade: devel
confinement: strict

plugs:
  system-config:
    interface: system-files
    read:
        - /etc/passwd
        - /etc/group
        - /etc/shadow
        - /etc/shadow-
        - /var/lib/extrausers/passwd
        - /var/lib/extrausers/group
        - /var/lib/extrausers/shadow
  cups-domain-socket:
    interface: system-files
    write:
        - /run/cups
        - /var/run/cups

apps:
  cupsd:
    command: scripts/run-cupsd
    stop-command: scripts/stop-cupsd
    reload-command: scripts/reload-cupsd
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, avahi-control, raw-usb, system-config, cups-domain-socket]
  cups-browsed:
    command: scripts/run-cups-browsed
    stop-command: scripts/stop-cups-browsed
    reload-command: scripts/reload-cups-browsed
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, avahi-control, system-config, cups-domain-socket, cups-control]
  lpinfo:
    command: lpinfo
    plugs: [network, avahi-control, raw-usb, system-config, cups-domain-socket]
  lpadmin:
    command: lpadmin
    plugs: [network, avahi-control, home, system-config, cups-domain-socket, cups-control]
  lpstat:
    command: lpstat
    plugs: [network, avahi-control, system-config, cups-domain-socket]
  lpoptions:
    command: lpoptions
    plugs: [network, avahi-control, home, system-config, cups-domain-socket]
  lp:
    command: lp
    plugs: [network, avahi-control, home, system-config, cups-domain-socket]
  cancel:
    command: cancel
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsenable:
    command: cupsenable
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsdisable:
    command: cupsdisable
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsaccept:
    command: cupsaccept
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsreject:
    command: cupsreject
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  accept:
    command: cupsaccept
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  reject:
    command: cupsreject
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsctl:
    command: cupsctl
    plugs: [network, avahi-control, system-config, cups-domain-socket, cups-control]
  cupsfilter:
    command: cupsfilter
    plugs: [network, avahi-control, home, system-config, cups-domain-socket]
  cupstestppd:
    command: cupstestppd
    plugs: [network, avahi-control, home, system-config, cups-domain-socket]
  ipptool:
    command: ipptool
    plugs: [network, avahi-control, home, system-config, cups-domain-socket]
  ippfind:
    command: ippfind
    plugs: [network, avahi-control, system-config, cups-domain-socket]
  ippeveprinter:
    command: ippeveprinter
    plugs: [network, network-bind, avahi-control, home, raw-usb, system-config, cups-domain-socket]
  gs:
    command: gs
    plugs: [home, system-config]

parts:
  cups-patches:
    plugin: dump
    source: patches
    organize:
      '*' : patches/
    override-prime: ""
  cups:
    source: https://github.com/apple/cups/releases/download/v2.3.3/cups-2.3.3-source.tar.gz
    plugin: autotools
    override-build: |
        set -eux
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-pass-on-ld-library-path.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-pass-on-path.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-allow-root-as-cups-user.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-allow-group-and-systemgroup-be-the-same.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/libcups-do-not-read-cupsd-conf-from-local-file.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/cups-deviced-allow-run-by-root.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cups-airprint-support.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-extra-check-for-admin-tasks-snap-cups-control.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/libcups-fix-convert-option-choice-names-in-ppd.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-fix-load-cupsd.conf.patch
        sed -i 's|fchown(cupsFileNumber(fp), getuid(), Group)|0|g' scheduler/file.c
        sed -i 's|(fchmod(cupsFileNumber(fp), mode))|(0)|g' scheduler/file.c
        sed -i 's|chown(filename, user, group)|0|g' scheduler/conf.c
        sed -i 's|setgroups(1, &Group)|0|g' scheduler/process.c
        sed -i 's|setgroups(1, &gid)|0|g' scheduler/cups-exec.c
        sed -i 's|fchown(|// fchown(|g' cups/*.c
        sed -i 's|chown(|// chown(|g' cups/*.c
        sed -i 's|fchmod(|// fchmod(|g' cups/*.c
        sed -i 's|chmod(|// chmod(|g' cups/*.c
        sed -i 's|fchown(|// fchown(|g' scheduler/*.c
        sed -i 's|fchmod(|// fchmod(|g' scheduler/*.c
        sed -i 's|"\$sysconfdir/cups")|"/var/snap/printing-stack-snap/common/etc/cups")|g' config-scripts/cups-directories.m4
        autoconf
        snapcraftctl build
    stage:
        - -var/spool/cups/tmp
    configflags:
        - --with-system-groups=root
        - --disable-pam
        #- --enable-debug-printfs
    build-packages:
        - patch
        - autoconf
        - automake
        - libtool
        - autotools-dev
        - pkg-config
        - ghostscript
        - libavahi-client-dev
        - libavahi-common-dev
        - libavahi-compat-libdnssd-dev
        - libdbus-1-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgnutls28-dev
        - libijs-dev
        - libjpeg-dev
        - libldap2-dev
        - libkrb5-dev
        - libpam0g-dev
        - libpaper-dev
        - libpng-dev
        - libsystemd-dev
        - libtiff5-dev
        - libusb-1.0-0-dev
        - po4a
        - po-debconf
        - poppler-utils
        - sharutils
        - zlib1g-dev
        - wget
        - libapparmor-dev
        - libsnapd-glib-dev
    stage-packages:
        - libusb-1.0-0
        - libavahi-common3
        - libavahi-client3
        - libicu60
        - libjson-glib-1.0-0
        - libsnapd-glib1
        - libsoup2.4-1
        - libxml2
    after: [cups-patches]
  qpdf:
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.0.1/qpdf-10.0.1.tar.gz
    plugin: autotools
    build-packages:
        - libjpeg-dev
        - zlib1g-dev
    stage-packages:
        - libjpeg-turbo8
  ghostscript:
    source: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs952/ghostscript-9.52.tar.gz
    plugin: autotools
    configflags:
        - --without-x
        - --disable-gtk
        - --with-drivers=pdfwrite,ps2write,cups,pwgraster,pxlmono,pxlcolor
        - --enable-cups
        - --enable-freetype
        - --datarootdir=/snap/printing-stack-snap/current/share/
        - --with-fontpath=/snap/printing-stack-snap/current/share/cups/fonts
        - --with-cups-serverbin=/snap/printing-stack-snap/current/lib/cups
        - --with-cups-serverroot=/var/snap/printing-stack-snap/common/etc/cups
        - --with-cups-datadir=/snap/printing-stack-snap/current/share/cups
    stage-packages:
        - libpaper1
        - libfontconfig1
        - libfreetype6
        - libpng16-16
    organize:
      snap/printing-stack-snap/current/share: share
    after: [cups]
  cups-filters:
    source: http://www.openprinting.org/download/cups-filters/cups-filters-1.27.4.tar.xz
    plugin: autotools
    configflags:
        - --disable-mutool
    build-packages:
        - autoconf
        - autotools-dev
        - pkg-config
        - sharutils
        - poppler-utils
        - libglib2.0-dev
        - liblcms2-dev
        - libldap2-dev
        - libpoppler-private-dev
        - libpoppler-cpp-dev
        - libjpeg-dev
        - libpng-dev
        - libtiff5-dev
        - libijs-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libdbus-1-dev
        - libavahi-common-dev
        - libavahi-client-dev
        - libavahi-glib-dev
        - librsvg2-bin
        - liblouis-dev
    stage-packages:
        - poppler-utils
        - libpoppler-cpp0v5
        - libasn1-8-heimdal
        - libavahi-glib1
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libkrb5-26-heimdal
        - libldap-2.4-2
        - libroken18-heimdal
        - libsasl2-2
        - libwind0-heimdal
        - libdb5.3
    after: [cups, qpdf, ghostscript]
  selected-fonts: # Temporary, fonts should come from the system
    plugin: nil
    source: .
    stage-packages:
        - fonts-freefont-ttf
    organize:
      usr/share/fonts/truetype/freefont/: share/cups/fonts/
    prime:
        - share/cups/fonts/*
  utils:
    plugin: nil
    source: .
    stage-packages:
        - lsof
        - perl-base
        - sed
        - grep
        - libbinutils
        - libmpfr6
        - libisl19
        - libmpc3
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
        - bin/
        - lib/
        - share/
  scripts:
    plugin: dump
    source: scripts/
    override-build: |
        set -eux
        gcc -o port-occupied port-occupied.c
        snapcraftctl build
    organize:
      run-cupsd: scripts/run-cupsd
      stop-cupsd: scripts/stop-cupsd
      reload-cupsd: scripts/reload-cupsd
      run-cups-browsed: scripts/run-cups-browsed
      stop-cups-browsed: scripts/stop-cups-browsed
      reload-cups-browsed: scripts/reload-cups-browsed
      port-occupied: scripts/port-occupied
    prime:
      - scripts/
    build-packages:
        - gcc
    after: [cups, cups-filters, selected-fonts, utils]
