name: cups
base: core18 # The base snap is the execution environment for this snap
version: 0.1.0
summary: CUPS-based printing stack snap
description: Complete printing environment in a snap
grade: devel
confinement: strict

# System user for filters and backends to drop privileges, "lp" is not
# available in a Snap
# See https://forum.snapcraft.io/t/system-usernames/
system-usernames:
  snap_daemon: shared

environment:
  CUPS_SERVERROOT: /var/snap/cups/common/etc/cups
  CUPS_DATADIR: /snap/cups/current/share/cups
  CUPS_SERVERBIN: /snap/cups/current/lib/cups
  CUPS_FONTPATH: /snap/cups/current/share/cups/fonts
  FONTCONFIG_FILE: /var/snap/cups/common/etc/fonts/fonts.conf
  FONTCONFIG_PATH: /snap/cups/current/etc/fonts/conf.d
  FONTCONFIG_SYSROOT: /snap/cups/current/etc/fonts

plugs:
  # This is needed for the script which does the migration of the
  # configuration and print queues of a classically installed CUPS
  # when it is replaced by this CUPS Snap
  etc-cups:
    interface: system-files
    read:
        - /etc/cups

slots:
  # Provide the cups-control and cups slots for other snaps to connect to
  admin:
    interface: cups-control
  printing:
    interface: cups

apps:
  cupsd:
    command: scripts/run-cupsd
    stop-command: scripts/stop-cupsd
    reload-command: scripts/reload-cupsd
    restart-condition: always
    daemon: simple
    # We are plugging "snapd-control" temporarily here until we have the
    # final method to determine whether a client process plugs "cups-control"
    # in place
    plugs: [network, network-bind, avahi-control, raw-usb, etc-cups, mount-observe, snapd-control]
    slots: [admin, printing]
  cups-browsed:
    command: scripts/run-cups-browsed
    stop-command: scripts/stop-cups-browsed
    reload-command: scripts/reload-cups-browsed
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, network-manager-observe, avahi-control, cups-control]
  lpinfo:
    command: lpinfo
    plugs: [network, avahi-control, raw-usb, cups-control]
  lpadmin:
    command: lpadmin
    plugs: [network, avahi-control, home, cups-control]
  lpstat:
    command: lpstat
    plugs: [network, avahi-control, cups-control]
  lpq:
    command: lpq
    plugs: [network, avahi-control, cups-control]
  lpc:
    command: lpc
    plugs: [network, avahi-control, cups-control]
  lpoptions:
    command: lpoptions
    plugs: [network, avahi-control, home, cups-control]
  lp:
    command: lp
    plugs: [network, avahi-control, home, cups-control]
  lpr:
    command: lpr
    plugs: [network, avahi-control, home, cups-control]
  cancel:
    command: cancel
    plugs: [network, avahi-control, cups-control]
  lprm:
    command: lprm
    plugs: [network, avahi-control, cups-control]
  cupsenable:
    command: cupsenable
    plugs: [network, avahi-control, cups-control]
  cupsdisable:
    command: cupsdisable
    plugs: [network, avahi-control, cups-control]
  cupsaccept:
    command: cupsaccept
    plugs: [network, avahi-control, cups-control]
  cupsreject:
    command: cupsreject
    plugs: [network, avahi-control, cups-control]
  accept:
    command: cupsaccept
    plugs: [network, avahi-control, cups-control]
  reject:
    command: cupsreject
    plugs: [network, avahi-control, cups-control]
  cupsctl:
    command: cupsctl
    plugs: [network, avahi-control, cups-control]
  cupsfilter:
    command: cupsfilter
    plugs: [network, avahi-control, home, cups-control]
  cupstestppd:
    command: cupstestppd
    plugs: [network, avahi-control, home, cups-control]
  ipptool:
    command: ipptool
    plugs: [network, avahi-control, home, cups-control]
  ippfind:
    command: ippfind
    plugs: [network, avahi-control, cups-control]
  driverless:
    command: driverless
    plugs: [network, avahi-control, cups-control]
  ippeveprinter:
    command: ippeveprinter
    plugs: [network, network-bind, avahi-control, home, raw-usb, cups-control]
  gs:
    command: gs
    plugs: [home, etc-cups]

parts:
  patches:
    plugin: dump
    source: patches
    organize:
      '*' : patches/
    override-prime: ""
  cups:
    source: https://github.com/apple/cups/releases/download/v2.3.3/cups-2.3.3-source.tar.gz
    plugin: autotools
    override-build: |
        set -eux
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-pass-on-ld-library-path.patch
        patch -p0 < $SNAPCRAFT_STAGE/patches/cupsd-pass-on-path.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-certs-dir-root-owned-and-writable.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-certs-files-group-root-no-acls.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-extra-check-for-admin-tasks-snap-cups-control.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cups-cupsfilter-pass-on-path-and-ld-library-path.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cups-airprint-support.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/libcups-fix-convert-option-choice-names-in-ppd.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cupsd-fix-load-cupsd.conf.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/cups-lpoptions-list-options-when-port-is-non-standard.patch
        patch -p1 < $SNAPCRAFT_STAGE/patches/libcups-resolve-dnssd-uri-from-localhost.patch
        sed -i 's|setgroups(1, &Group)|setgroups(0, NULL)|g' scheduler/process.c
        sed -i 's|setgroups(1, &gid)|setgroups(0, NULL)|g' scheduler/cups-exec.c
        sed -i 's|"\$sysconfdir/cups")|"/var/snap/cups/common/etc/cups")|g' config-scripts/cups-directories.m4
        rm configure
        autoconf
        snapcraftctl build
    configflags:
        - --with-system-groups=root
        - --disable-pam
        - --disable-systemd
        - --without-rcdir
        - --with-docdir=/share/cups/doc
        #- --enable-debug-printfs
    build-packages:
        - patch
        - autoconf
        - automake
        - libtool
        - autotools-dev
        - pkg-config
        - g++
        - ghostscript
        - libavahi-client-dev
        - libavahi-common-dev
        - libavahi-compat-libdnssd-dev
        - libdbus-1-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgnutls28-dev
        - libijs-dev
        - libjpeg-dev
        - libldap2-dev
        - libkrb5-dev
        - libpam0g-dev
        - libpaper-dev
        - libpng-dev
        - libsystemd-dev
        - libtiff5-dev
        - libusb-1.0-0-dev
        - po4a
        - po-debconf
        - poppler-utils
        - sharutils
        - zlib1g-dev
        - wget
        - libapparmor-dev
        - libsnapd-glib-dev
    stage-packages:
        - libusb-1.0-0
        - libavahi-common3
        - libavahi-client3
        - libicu60
        - libjson-glib-1.0-0
        - libsnapd-glib1
        - libsoup2.4-1
        - libxml2
    prime:
        - -etc/fonts
        - -var
        - -include
        - -share/man
        - -share/doc
        - -share/lintian
        - -usr/share/fonts
        - -usr/share/man
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
    after: [patches]
  qpdf:
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.0.1/qpdf-10.0.1.tar.gz
    plugin: autotools
    build-packages:
        - g++
        - libjpeg-dev
        - zlib1g-dev
    stage-packages:
        - libjpeg-turbo8
    prime:
        - -etc/fonts
        - -var
        - -include
        - -share/man
        - -share/doc
        - -share/lintian
        - -usr/share/fonts
        - -usr/share/man
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -lib/libqpdf.a
  ghostscript:
    source: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9533/ghostscript-9.53.3.tar.gz
    plugin: autotools
    configflags:
        - --without-x
        - --disable-gtk
        - --with-drivers=pdfwrite,ps2write,cups,pwgraster,pxlmono,pxlcolor
        - --enable-cups
        - --enable-freetype
        - --datarootdir=/snap/cups/current/share/
        - --with-fontpath=/snap/cups/current/share/cups/fonts
        - --with-cups-serverbin=/snap/cups/current/lib/cups
        - --with-cups-serverroot=/var/snap/cups/common/etc/cups
        - --with-cups-datadir=/snap/cups/current/share/cups
    stage-packages:
        - libpaper1
        - libfontconfig1
        - libfreetype6
        - libpng16-16
    prime:
        - -etc/fonts
        - -var
        - -include
        - -share/man
        - -share/doc
        - -share/lintian
        - -usr/share/fonts
        - -usr/share/man
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -snap/cups
    organize:
      snap/cups/current/share: share
    after: [patches, cups]
  cups-filters:
    source: http://www.openprinting.org/download/cups-filters/cups-filters-1.28.5.tar.xz
    plugin: autotools
    configflags:
        - --disable-mutool
        - --without-rcdir
        - --with-pdftops-path=/snap/cups/current/usr/bin/pdftops
    build-packages:
        - autoconf
        - autotools-dev
        - pkg-config
        - g++
        - sharutils
        - poppler-utils
        - libglib2.0-dev
        - liblcms2-dev
        - libldap2-dev
        - libpoppler-private-dev
        - libpoppler-cpp-dev
        - libjpeg-dev
        - libpng-dev
        - libtiff5-dev
        - libijs-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libdbus-1-dev
        - libavahi-common-dev
        - libavahi-client-dev
        - libavahi-glib-dev
        - librsvg2-bin
        - liblouis-dev
    stage-packages:
        - poppler-utils
        - libpoppler-cpp0v5
        - libasn1-8-heimdal
        - libavahi-glib1
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libkrb5-26-heimdal
        - libldap-2.4-2
        - libroken18-heimdal
        - libsasl2-2
        - libwind0-heimdal
        - libdb5.3
    prime:
        - -etc/fonts
        - -var
        - -include
        - -share/man
        - -share/doc
        - -share/lintian
        - -usr/share/fonts
        - -usr/share/man
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -lib/libcupsfilters.a
        - -lib/libfontembed.a
    after: [cups, qpdf, ghostscript]
  selected-fonts: # Temporary, fonts should come from the system
    plugin: nil
    source: .
    stage-packages:
        - fonts-freefont-ttf
        - fonts-arphic-uming
        - fontconfig-config
    organize:
      usr/share/fonts/truetype/freefont/: share/cups/fonts/
      usr/share/fonts/truetype/arphic/: share/cups/fonts/
    prime:
        - etc/fonts/*
        - share/cups/fonts/*
  utils:
    plugin: nil
    source: .
    stage-packages:
        - perl-base
        - sed
        - grep
        - libbinutils
        - libmpfr6
        - libisl19
        - libmpc3
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
        - bin/
        - lib/
        - share/
        - -share/gdb
        - -share/info
        - -share/man
        - -share/doc
        - -share/lintian
  scripts:
    plugin: dump
    source: scripts/
    override-build: |
        set -eux
        gcc -o port-occupied port-occupied.c
        snapcraftctl build
    organize:
      run-cupsd: scripts/run-cupsd
      stop-cupsd: scripts/stop-cupsd
      reload-cupsd: scripts/reload-cupsd
      run-cups-browsed: scripts/run-cups-browsed
      stop-cups-browsed: scripts/stop-cups-browsed
      reload-cups-browsed: scripts/reload-cups-browsed
      port-occupied: scripts/port-occupied
    prime:
      - scripts/
    build-packages:
        - gcc
    after: [cups, cups-filters, selected-fonts, utils]
