name: cups
base: core20 # The base snap is the execution environment for this snap
version: 0.1.0
summary: CUPS-based printing stack snap
description: Complete printing environment in a snap
grade: devel
confinement: strict

# Only build on the architectures supported
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

# System user for filters and backends to drop privileges, "lp" is not
# available in a Snap
# See https://forum.snapcraft.io/t/system-usernames/
system-usernames:
  snap_daemon: shared

# Make fontconfig for the texttopdf and bannertopdf filters working by
# mirroring the needed directories to the placed where libfontconfig is
# searching for them
# Also make resolution of ".local" host names (Zero-Conf/mDNS/DNS-SD)
# working: Mirror nsswitch.conf with added mDNS look-up support into
# /etc/nsswitch.conf
# See: https://forum.snapcraft.io/t/no-mdns-support-in-snaps-should-core-have-a-modified-nsswitch-conf/
layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig
  /etc/nsswitch.conf:
    bind-file: $SNAP/etc/nsswitch.conf
  /etc/papersize:
    bind-file: $SNAP_COMMON/etc/papersize

environment:
  CUPS_SERVERROOT: /var/snap/cups/common/etc/cups
  CUPS_DATADIR: /snap/cups/current/share/cups
  CUPS_SERVERBIN: /snap/cups/current/lib/cups

plugs:
  # This interface is needed for checking whether CUPS in this
  # Snap should run as a proxy for the system's CUPS or whether
  # this Snap's CUPS is the standard CUPS for the system.
  # This interface also serves for scripts which do a migration
  # of the configuration and print queues of a classically
  # installed CUPS when it is replaced by this CUPS Snap
  etc-cups:
    interface: system-files
    read:
      - /etc/cups
  # Alias name for the utilities to plug cups-control while we also have a
  # slot named cups-control. This plug is needed especially so that the
  # utilities included with this Snap can also do admin tasks on a CUPS
  # daemon which is not from this Snap
  cups-internal:
    interface: cups-control

slots:
  # Provide the cups-control and cups slots for other snaps to connect to
  cups-control:
    interface: cups-control
  cups:
    interface: cups

apps:
  cupsd:
    command: scripts/run-cupsd
    stop-command: scripts/stop-cupsd
    reload-command: scripts/reload-cupsd
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, avahi-control, raw-usb, etc-cups]
  cups-browsed:
    command: scripts/run-cups-browsed
    stop-command: scripts/stop-cups-browsed
    reload-command: scripts/reload-cups-browsed
    restart-condition: always
    daemon: simple
    plugs: [network, network-bind, network-manager-observe, avahi-control, cups-internal]
  lpinfo:
    command: scripts/run-util sbin/lpinfo
    plugs: [network, cups-internal]
  lpadmin:
    command: scripts/run-util sbin/lpadmin
    plugs: [network, avahi-control, home, cups-internal]
  lpstat:
    command: scripts/run-util bin/lpstat
    plugs: [network, avahi-control, cups-internal]
  lpq:
    command: scripts/run-util bin/lpq
    plugs: [network, cups-internal]
  lpc:
    command: scripts/run-util sbin/lpc
    plugs: [network, cups-internal]
  lpoptions:
    command: scripts/run-util bin/lpoptions
    plugs: [network, home, cups-internal]
  lp:
    command: scripts/run-util bin/lp
    plugs: [network, home, cups-internal]
  lpr:
    command: scripts/run-util bin/lpr
    plugs: [network, home, cups-internal]
  cancel:
    command: scripts/run-util bin/cancel
    plugs: [network, cups-internal]
  lprm:
    command: scripts/run-util bin/lprm
    plugs: [network, cups-internal]
  cupsenable:
    command: scripts/run-util sbin/cupsenable
    plugs: [network, cups-internal]
  cupsdisable:
    command: scripts/run-util sbin/cupsdisable
    plugs: [network, cups-internal]
  cupsaccept:
    command: scripts/run-util sbin/cupsaccept
    plugs: [network, cups-internal]
  cupsreject:
    command: scripts/run-util sbin/cupsreject
    plugs: [network, cups-internal]
  accept:
    command: scripts/run-util sbin/cupsaccept
    plugs: [network, cups-internal]
  reject:
    command: scripts/run-util sbin/cupsreject
    plugs: [network, cups-internal]
  cupsctl:
    command: scripts/run-util sbin/cupsctl
    plugs: [network, cups-internal]
  cupsfilter:
    command: scripts/run-util sbin/cupsfilter
    plugs: [network, home, cups-internal]
  cupstestppd:
    command: scripts/run-util bin/cupstestppd
    plugs: [network, home, cups-internal]
  ipptool:
    command: scripts/run-util bin/ipptool
    plugs: [network, avahi-control, home, cups-internal]
  ippfind:
    command: scripts/run-util bin/ippfind
    plugs: [network, avahi-control, cups-internal]
  driverless:
    command: scripts/run-util bin/driverless
    plugs: [network, avahi-control, cups-internal]
  ippeveprinter:
    command: scripts/run-util bin/ippeveprinter
    plugs: [network, network-bind, avahi-control, home, raw-usb, cups-internal]
  gs:
    command: bin/gs
    plugs: [home, etc-cups]

parts:
  snapd-glib:
    source: https://github.com/snapcore/snapd-glib
    source-type: git
    plugin: meson
    meson-parameters:
      - -Dprefix=/
      - -Dbuildtype=plain
      - -Dintrospection=false
      - -Ddocs=false
      - -Dvala-bindings=false
      - -Dqt-bindings=false
      - -Dqml-bindings=false
    build-packages:
      - libglib2.0-dev
      - libjson-glib-dev
      - libsoup2.4-dev
    stage-packages:
      - libicu66
      - libjson-glib-1.0-0
      - libsoup2.4-1
      - libxml2
    prime:
      - -include
      - -libexec
      - -share
  cups:
    source: https://github.com/OpenPrinting/cups.git
    source-type: git
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
      - --exec-prefix=/
      - --datadir=/share
      - --datarootdir=/share
      - --includedir=/include
      - --sysconfdir=/var/snap/cups/common/etc
      - --with-system-groups=root
      - --enable-libpaper
      - --disable-pam
      - --disable-systemd
      - --without-rcdir
      - --with-docdir=/share/cups/doc
      - --with-container=snap
      #- --enable-debug-printfs
    build-packages:
      - patch
      - autoconf
      - automake
      - libtool
      - autotools-dev
      - pkg-config
      - g++
      - libavahi-client-dev
      - libavahi-common-dev
      - libavahi-compat-libdnssd-dev
      - libdbus-1-dev
      - libgnutls28-dev
      - libkrb5-dev
      - libpam0g-dev
      - libpaper-dev
      - libsystemd-dev
      - libusb-1.0-0-dev
      - po4a
      - po-debconf
      - zlib1g-dev
      - libapparmor-dev
      - libsnapd-glib-dev
    stage-packages:
      - libusb-1.0-0
      - libavahi-common3
      - libavahi-client3
      - libpaper1
    organize:
      var/snap/cups/common/etc: etc
    prime:
      - -etc/fonts
      - -var
      - -include
      - -share/man
      - -share/doc
      - -share/lintian
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
    after: [snapd-glib]
  qpdf:
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
    build-packages:
      - g++
      - libjpeg-dev
      - zlib1g-dev
    stage-packages:
      - libjpeg-turbo8
    prime:
      - -etc/fonts
      - -var
      - -include
      - -share/man
      - -share/doc
      - -share/lintian
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -lib/libqpdf.a
  ghostscript:
    source: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9540/ghostscript-9.54.0.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
      - --without-x
      - --disable-gtk
      - --with-drivers=pdfwrite,ps2write,cups,pwgraster,pxlmono,pxlcolor
      - --enable-cups
      - --enable-freetype
      - --without-tesseract
      - --datarootdir=/snap/cups/current/share/
      - --with-fontpath=/snap/cups/current/share/cups/fonts
      - --with-cups-serverbin=/snap/cups/current/lib/cups
      - --with-cups-serverroot=/var/snap/cups/common/etc/cups
      - --with-cups-datadir=/snap/cups/current/share/cups
    stage-packages:
      - libpaper1
      - libfontconfig1
      - libfreetype6
      - libpng16-16
    prime:
      - -etc/fonts
      - -var
      - -include
      - -share/man
      - -share/doc
      - -share/lintian
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -snap/cups
    organize:
      snap/cups/current/share: share
    after: [cups]
  cups-filters:
    source: https://github.com/OpenPrinting/cups-filters/releases/download/1.28.10/cups-filters-1.28.10.tar.xz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/
      - --exec-prefix=/
      - --datadir=/share
      - --datarootdir=/share
      - --includedir=/include
      - --disable-mutool
      - --without-rcdir
      - --with-pdftops-path=/snap/cups/current/usr/bin/pdftops
    build-packages:
      - autoconf
      - autotools-dev
      - pkg-config
      - g++
      - sharutils
      - poppler-utils
      - libglib2.0-dev
      - liblcms2-dev
      - libldap2-dev
      - libpoppler-private-dev
      - libpoppler-cpp-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff5-dev
      - libijs-dev
      - zlib1g-dev
      - libfontconfig1-dev
      - libdbus-1-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libavahi-glib-dev
      - librsvg2-bin
      - liblouis-dev
    stage-packages:
      - poppler-utils
      - libpoppler-cpp0v5
      - libasn1-8-heimdal
      - libavahi-glib1
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libroken18-heimdal
      - libsasl2-2
      - libwind0-heimdal
      - libdb5.3
      - fonts-freefont-ttf
      - fonts-arphic-uming
      - fontconfig-config
    organize:
      var/snap/cups/common/etc: etc
    prime:
      - -var
      - -include
      - -share/man
      - -share/doc
      - -share/lintian
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -lib/libcupsfilters.a
      - -lib/libfontembed.a
    after: [cups, qpdf, ghostscript]
  utils:
    plugin: nil
    source: .
    stage-packages:
      - perl-base
      - sed
      - grep
      - libbinutils
      - libmpfr6
      - libisl22
      - libmpc3
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
      usr/share/: share/
    prime:
      - bin/
      - lib/
      - share/
      - -share/gdb
      - -share/info
      - -share/man
      - -share/doc
      - -share/lintian
  mdns-lookup:
    # Make resolution of ".local" host names (Zero-Conf/mDNS/DNS-SD)
    # working: Take the original nsswitch.conf file from the base
    # Snap and add "mdns4_minimal [NOTFOUND=return]" to its "hosts:" line
    # Also install corresponding mdns4_minimal plug-in
    # See: https://forum.snapcraft.io/t/no-mdns-support-in-snaps-should-core-have-a-modified-nsswitch-conf/
    plugin: nil
    stage-packages:
      - libnss-mdns
    override-prime: |
      set -eux
      sed -Ee 's/^\s*hosts:(\s+)files/hosts:\1files mdns4_minimal \[NOTFOUND=return\]/' /snap/core20/current/etc/nsswitch.conf > $SNAPCRAFT_STAGE/etc/nsswitch.conf
      snapcraftctl prime
    prime:
      - lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_mdns4_minimal*
      - etc/nsswitch.conf
  scripts:
    plugin: dump
    source: scripts/
    override-build: |
      set -eux
      gcc -o port-occupied port-occupied.c
      snapcraftctl build
    organize:
      run-cupsd: scripts/run-cupsd
      stop-cupsd: scripts/stop-cupsd
      reload-cupsd: scripts/reload-cupsd
      run-cups-browsed: scripts/run-cups-browsed
      stop-cups-browsed: scripts/stop-cups-browsed
      reload-cups-browsed: scripts/reload-cups-browsed
      run-util: scripts/run-util
      port-occupied: scripts/port-occupied
    prime:
      - scripts/
    build-packages:
      - gcc
    after: [cups, cups-filters, utils]
  cups-proxyd:
    plugin: make
    source: cups-proxyd
    build-packages:
      - gcc
      - libglib2.0-dev
      - libavahi-common-dev
      - libavahi-client-dev
      - libavahi-glib-dev
    organize:
      usr/lib/cups/backend: lib/cups/backend
      usr/sbin: sbin
    after: [cups, cups-filters]
