#! /bin/sh

set -e -x

# Exit if we are already shutting down cupsd
if [ -f "${SNAP_COMMON}/pid/stop-cupsd.lock" ]; then
    echo "==> We are already shutting down cupsd"
    exit 0
fi
touch "${SNAP_COMMON}/pid/stop-cupsd.lock"

# Shut down cups-browsed first, so that it can remove its temporary queues
# before CUPS shuts down
echo "==> Shutting down cups-browsed first"
$SNAP/stop-cups-browsed

# Shut down CUPS
echo "==> Shutting down CUPS"
PID=$(cat "${SNAP_COMMON}/pid/cupsd.pid" || true)
if [ -n "${PID}" ] && kill -0 "${PID}" 2>/dev/null; then
    kill -TERM "${PID}"

    DEAD=0
    for i in $(seq 30); do
        if ! kill -0 "${PID}" 2>/dev/null; then
            DEAD=1
            break
        fi
        sleep 1
    done

    if [ "${DEAD}" = "0" ]; then
        echo "==> Forcefully killing CUPS after 30 seconds wait"
        kill -9 "${PID}"
    fi
fi

# Removing PID file
rm -f "${SNAP_COMMON}/pid/cupsd.pid"
rm -f "${SNAP_COMMON}/pid/stop-cupsd.lock"
